include:
  - path: docker-compose.base.yml

services:
  api:
    extends:
      file: docker-compose.services.yml
      service: api
    image: reflyai/refly-api:latest

  web:
    extends:
      file: docker-compose.services.yml
      service: web
    image: reflyai/refly-web:latest
    ports:
      - 5700:80
